#+TITLE: Zig Invaders

This is a simple space invaders clone written in zig that is meant to showcase
the features of Zig. This program was written by following along with this
YouTube series: [[https://www.youtube.com/watch?v=eZLTAhlFwlI&list=PLYA3HD4nElQnxWnznih9w0RloSw0hFaYQ&index=1][Zig invaders]].

Here are some notes I took while following along with this series:

* Lesson 1
  To begin this project we ran ~zig init~ in this directory. This generated the
  following files:
  #+name: tree
  #+begin_src shell :exports output :results raw
    tree
  #+end_src

  #+RESULTS: tree
  .
  ├── build.zig
  ├── build.zig.zon
  └── src
      ├── main.zig
      └── root.zig

  2 directories, 5 files

  The first of these files to explore is the ~build.zig~. This is our build
  configuration file. You can think of this file like our Makefile, but this
  build file is written in Zig itself!

  The next file to take a look at is the ~build.zig.zon~. This is essentially
  our package manifest file. It defines our package name, version, and
  dependencies. You may be wondering what is ~zon~ or maybe you have already
  guessed, but ~zon~ stands for "Zig Object Notation". It is a specific notation
  that is built for Zig.

  If you come from a JavaScript background you may notice that this is similar
  to your ~package.json~ in some ways. The ~build.zig~ is a lot like the steps
  block of a ~package.json~ and the ~zon~ file is a lot like the rest of a
  ~package.json~ file.

** src directory
   Now that we have covered the build files let's take a look at the ~src~
   directory. In our case we see a ~main.zig~ and a ~root.zig~. This is just a
   convention that you can change this if you like. Conventionally
   ~main.zig~ is going to be your executable, whereas ~root.zig~ if your
   library. If you were going to be writing some library code and were following
   convention you would put that in ~root.zig~.

* Lesson 2
  In this lesson we cover adding graphics capabilities to our zig program using
  raylib. Raylib is a simple and easy-to-use library to enjoy videogames
  programming, written in C. Raylib also provides Zig bindings and Zig also has
  excellent interoperability with C.

  With this in mind we essentially have two options. We can either import Raylib
  directly using some of Zig's builtins for working with C code or we could
  using bindings. Bindings are essentially a library where someone has done the
  heavy lifting of importing that C code into Zig and then they repackage it in
  a way that is usually more Zig friendly.

  For this program we are going to stick with the Zig bindings, but if you are a
  more experienced Zig developer you could import Raylib directly from C or to
  build this out as intended and then replace the Raylib Zig bindings with C
  bindings.

** Adding dependencies
   To add dependencies to a Zig program you essentially you have two options:
   1. You can open your ~zig.build.zon~ and add the package to the dependencies
      section of the zon file.
   2. Another option is to use ~zig fetch~.

   In this project we will be using ~zig fetch~. The command we used to add
   raylib was:
   #+begin_src shell
     zig fetch --save git+https://www.github.com/raylib-zig/raylib-zig#devel
   #+end_src

   ~devel~ in this case is the git branch we want to pull from for our
   dependency.

   After running the above if you look in your zon file you will see something
   like this:
   #+begin_example
     .raylib_zig = .{
         .url = "git+https://www.github.com/raylib-zig/raylib-zig?ref=devel#cd71c85d571027ac8033357f83b124ee051825b3",
         .hash = "raylib_zig-5.6.0-dev-KE8REENOBQC-m5nK7M2b5aKSIubJPbPLUYcRhT7aT3RN",
     },
   #+end_example

   This adds our dependency to our project, but you see after the git branch
   there is also a commit sha. This is so that we can reliably rebuild our
   application in the future by pinning to the specific commit on the devel
   branch.

   Unlike adding a package to your ~package.json~ in a JS project or your
   ~pyproject.toml~ in a Python project, just having this package listed in the
   zon file is not enough for it to be usable in Zig. In Zig we also have to
   make this package available to the executable. To do this we have to open our
   ~build.zig~ and add the dependency as a ~const~ to our ~build~ function. You
   should add something like this after the target and optimize ~const~'s:
   #+begin_src zig
     const raylib_dep = b.dependency("raylib_zig", .{
         .target = target,
         .optimize = optimize,
     });

     const raylib = raylib_dep.module("raylib");
     const raylib_artifact = raylib_dep.artifact("raylib");
   #+end_src

   What this is doing is saying is we are defining a module called ~raylib_dep~
   that is a dependency of ~raylib_zig~. We are then defining a ~const~ called
   ~raylib~ that points to a specific module in this dependency called
   "raylib". We are also defining a ~const~ called ~raylib_artifact~ that points
   to an artifact in this dependency called "raylib".

   Later on in our ~build.zig~ we in the exe const we would add something like
   this to add our raylib module to our exe:
   #+begin_src zig
     // Other lines above
     // ...
     .imports = &.{
         .{ .name = "zig_invaders", .module = mod },
         .{ .name = "raylib", .module = raylib },
     },
     // Other lines below
     // ...
   #+end_src

   We will also add the following line after our exe ~const~ to add our library
   artifact:
   #+begin_src zig
     exe.linkLibrary(raylib_artifact);
   #+end_src

   With all of this place we can run ~zig build~ to download and compile raylib
   and this will take a while the first it is run.

* Lesson 3
  In this lesson we will begin writing our ~main.zig~ and begin using raylib. In
  Zig we have ~const~ and we have ~var~ just like in many other languages. One
  thing to note about Zig is that when libraries or packages are imported they
  are assigned to a ~const~.

  Zig also has a large number of builtin functions and for the most part you
  will learn them as you encounter them, but if you wanted to see them you can
  go to: https://ziglang.org/documentation/master/#Builtin-Functions.

  One of these builtin functions that we will be using right now is the import
  function: https://ziglang.org/documentation/master/#import.

  Putting all of this together we can import raylib like this:
  #+begin_src zig
    const rl = @import("raylib");
  #+end_src
